POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "Vscode rest client request",
  "important": true
}

###
GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/6694b461a6d498683becafce

###
PUT http://localhost:3001/api/notes/
Content-Type: application/json

{
  "content": "Toggled",
  "important": false
}