POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "lol",
  "important": true
}

###
GET http://localhost:3001/api/notes

###
DELETE http://localhost:3001/api/notes/6694f6e66ce536f6f2e0e017

###
PUT http://localhost:3001/api/notes/66949b4fa660919821c59781
Content-Type: application/json

{
  "content": "Toggled",
  "important": false
}